### ISSUE TITLE
UnboundLocalError: local variable 'loc' referenced before assignment

### ISSUE THREAD

**Issue by mandalsumit17** [info3g/linkedin-scrapper#1]
Hi,

I am facing this issue while running the script, i have tried stating the variable as global but still facing a error mentioned below

Error Message :-
"
Going to scrape Page 1 data
Traceback (most recent call last):
  File "C:/Python27/Automation Testing/Scrapping.py", line 187, in <module>
    obJH.start()
  File "C:/Python27/Automation Testing/Scrapping.py", line 181, in start
    self.getData()
  File "C:/Python27/Automation Testing/Scrapping.py", line 115, in getData
    'heading': heading, 'loc': loc, 'website': website, 'phone': phone, 'email': email,
UnboundLocalError: local variable 'loc' referenced before assignment

Process finished with exit code 1
"

**Comment by info3g** [comment]
Hi Sumit,

You can simply defined ( loc = "" or loc = None)  before using loc variable. see the screenshot here: http://prntscr.com/pjfrwg .

if any UnboundLocalError occurs the you can simply defined all variuables like this

**Comment by mandalsumit17** [comment]
Hi ,

Thanks for the solution!
i have changed the location of the file, you can check in the screen attached below.

Previously it was : 'workbook = xlsxwriter.Workbook("linkedin-search-data.xlsx")'
Currently it is : workbook = xlsxwriter.Workbook("C:\\users\s.m\Desktop\test.xlsx")

When i run the process it shows that the data is scrapped but when i open the file its blank.
so can you please suggest me what changes shall i do for this?
I have attached the code file as well.

[Code.txt](https://github.com/info3g/linkedin-scrapper/files/3728195/Code.txt)





<img width="580" alt="Image1" src="https://user-images.githubusercontent.com/56578353/66814743-c1d89a00-ef54-11e9-88ac-0f1e34be0e07.PNG">
